- hello/templates/Admin/Orders/index.html
> Cambio de la url

- hello/templates/user/register.html
> MKP-79 Cambio de url

- hello/static/js/index.js
- hello/static/js/main.js
Advanced purchase on Catalogue.
> Advanced purchase on Catalogue.

- hello/templates/Admin/Orders/index.html
- hello/templates/Orders/index.html
Validación cuando el carrito no tenga órdenes
> Validación cuando el carrito no tenga órdenes

- hello/templates/header.html
Se agregó al header la consulta a los órdenes para un admin y para un usuario
> Modificación del Header

- .idea/workspace.xml
- hello/static/js/regProducer.js
- hello/templates/producer/mapProducer.html
Se agrega funcionalidad para que los nombres de los productores salgan en el mapa
> [FIX] - Nombre productores en el mapa

- gettingstarted/urls.py
- hello/static/js/index.js
- hello/static/js/producer_catalogue.js
- hello/templates/footer.html
- hello/templates/header.html
- hello/templates/producer_catalogue.html
- hello/views.py
Use {% load static%} for header and footer html templates.
> Use {% load static%} for header and footer html templates.

- hello/static/js/index.js
- hello/static/js/producer_catalogue.js
- hello/templates/producer_catalogue.html
- hello/views.py
Bug #MKP-238. Display products by producer.
> Bug #MKP-238. Display products by producer.

- gettingstarted/urls.py
- hello/serializers.py
- hello/static/js/cooperativas.js
- hello/templates/cooperatives.html
- hello/templates/header.html
- hello/views.py
Cooperatives menu for admin users. #MKP-239.
> Cooperatives menu for admin users. #MKP-239

- hello/serializers.py
- hello/static/js/baskets.js
- hello/templates/baskets.html
- hello/templates/header.html
- hello/views.py
MKP-72 : Create empty basket for admins done.
> MKP-72 : Create empty basket for admins done.

- gettingstarted/urls.py
- hello/serializers.py
- hello/templates/products/my_products.html
- hello/templates/products/updateProduct.html
- hello/views.py
Actualizar estado de la oferta
> Mkp 60. Actualizar estado de la oferta 

- .idea/modules.xml
- hello/templates/producer/regProducer.html
- hello/templates/user/register.html
Cambios en el html de Registro usuario y Productor
> Cambios en el html de Registro usuario y Productor

- gettingstarted/settings.py
- hello/tests_mkp_126.py
- hello/views.py
Ready to Test MKP-126 (Update Producer Info).
> Ready to Test MKP-126 (Update Producer Info).

- hello/models.py
- hello/templates/header.html
Ajuste para mostrar los productos del productor en el menú
> Mkp 59 Ajuste para mostrar los productos del productor en el menú

- hello/static/js/baskets.js
- hello/templates/baskets.html
MKP - 76 Modal to display the products that belongs to the selected basket.
> MKP - 76 Modal to display the products that belongs to the selected basket.

- gettingstarted/urls.py
- hello/static/js/edit-producer.js
- hello/static/js/producers.js
- hello/templates/EditProducerAdmin.html
- hello/views.py
MKP 126 - Edit producer option for Admin.
> Mkp 126/edit producer

- gettingstarted/settings.py
- hello/static/js/login.js
- hello/templates/login.html
- hello/templates/producer/regProducer.html
- hello/views.py
Se agregaron modales para los mensajes y validación cuando el usuario está inactivo
> Fix Login user inactive

- hello/views.py
Arreglo opciones usuario inactivo
> Arreglo opciones usuario inactivo

- gettingstarted/urls.py
- hello/services.py
- hello/templates/EditBasketsAdmin.html
- hello/views.py
> MKP-302: Precio estimado de canasta

- gettingstarted/urls.py
- hello/services.py
- hello/static/js/catalogue.js
- hello/static/js/index.js
- hello/templates/index.html
- hello/views.py
Display WeeklyStock products on Index and Catalogue.
> Display WeeklyStock products on Index and Catalogue.
